config/routes.rb
Rails.application.routes.draw do
  resources :commands
  root to: redirect("/commands")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction
  attr_reader :direction

  POSSIBILITIES = ['north', 'east', 'south', 'west']

  def initialize(direction)
    @direction = direction.to_s.downcase
  end

  def left?
    direction == "left"
  end

  def right?
    direction == "right"
  end
end

app/models/robot.rb
class Robot < ApplicationRecord
  def unplaced?
    face == nil
  end

  def place_at(x, y, given_face)
    x ||= position_x
    y ||= position_y
    given_face ||= face
    update(position_x: x, position_y: y, face: given_face.downcase)
  end

  def placed_at?(x, y)
    (position_x == x && position_y == y)
  end

  def next_move
    if north?
      [:y, position_y - 1]
    elsif south?
      [:y, position_y + 1]
    elsif west?
      [:x, position_x - 1]
    else
      [:x, position_x + 1]
    end
  end

  def rotate_to(direction)
    new_direction = if direction.left?
      Direction::POSSIBILITIES.index(face) - 1
    else
      Direction::POSSIBILITIES.index(face) + 1
    end
    update(face: Direction::POSSIBILITIES.fetch(new_direction, Direction::POSSIBILITIES.first))
  end

  def north?
    face == 'north'
  end

  def south?
    face == 'south'
  end

  def west?
    face == 'west'
  end

  def east?
    face == 'east'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  def index
    @robot = Robot.create
  end

  def create
    command = Command.new(command_params[:command], robot)

    if command.execute
      @robot = command.robot
      render :index
    else
      head 400
    end
  end

  private

  def robot
    Robot[command_params[:robot_id]]
  end

  def command_params
    params.permit(:command, :robot_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/index.haml
.center
  %table.table
    - Table.y_min.upto(Table.y_max) do |y|
      %tr
        - Table.x_min.upto(Table.x_max) do |x|
          %td
            - if @robot.placed_at?(x, y)
              %span{class: @robot.face}
                = ">"

  = form_with url: commands_path do |form|
    = form.label :command
    = form.text_field :command, autofocus: true, autocomplete: :off
    = form.hidden_field :robot_id, value: @robot.id
    = form.submit "Send"

    .error
      %p

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyRobot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>